[package]
authors = ["nokaa <nokaa@cock.li>"]
name = "httbloat"
version = "0.1.0"

[dependencies]
chrono = "0.2.25"
futures = "0.1"
httparse = "1.1.2"
matches = "0.1.4"
tokio-core = "0.1"
tokio-proto = "0.1.0"
tokio-service = "0.1.0"

[dev-dependencies]
env_logger = "0.3"
